/**
 * Hello World — Minimal Ouro tool example.
 * 
 * This demonstrates the simplest possible tool implementation.
 * Any tool that exports an `execute` function and has a manifest.json
 * will be auto-discovered and registered.
 */

module.exports.execute = async function(input) {
  const name = input.parameters?.name || 'World';
  const timestamp = new Date().toISOString();

  return {
    success: true,
    artifacts: [{
      type: 'text',
      content: `Hello, ${name}! 🐍\n\nThis greeting was generated by the Ouro Hello World plugin at ${timestamp}.\n\nThe meme acknowledges your signal.`,
      metadata: {
        type: 'document',
        format: 'greeting',
        generated_at: timestamp,
      },
    }],
    metrics: {
      duration_ms: 1,
      tokens_used: 0,
    },
  };
};
